import {
  Product,
  Category,
  Supplier,
  Customer,
  Location,
  Sale,
  PurchaseOrder,
  StockMovement,
  Expense,
  BusinessSettings,
  StockTransfer,
} from './types';

export const CLEAN_SETTINGS: BusinessSettings = {
  id: 'settings',
  businessName: 'Enterprise Store',
  ownerName: 'Store Manager',
  currencySymbol: '$',
  currencyCode: 'USD',
  language: 'en',
  theme: 'dark',
  taxRate: 8.5,
  primaryLocationId: 'loc_main',
  address: '100 Main Street, Suite 100',
  phone: '+1 (555) 010-0000',
  email: 'admin@enterprisestore.io',
  demoMode: false,
};

export const CLEAN_LOCATIONS: Location[] = [
  { id: 'loc_main', name: 'Main Store', code: 'MAIN-01', address: '100 Main Street', isMain: true },
];

export const CLEAN_CATEGORIES: Category[] = [
  { id: 'cat_gen', name: 'General Merchandise', description: 'Standard store products' },
  { id: 'cat_elec', name: 'Electronics & Tech', description: 'Electronic devices and accessories' },
  { id: 'cat_app', name: 'Apparel & Goods', description: 'Clothing, wear, and merchandise' },
];

export const CLEAN_SUPPLIERS: Supplier[] = [
  { id: 'sup_primary', name: 'Primary Wholesale Supplier', contactPerson: 'Account Representative', email: 'orders@wholesalesupplier.com', phone: '+1 800-555-0100', address: '500 Logistics Way', leadTimeDays: 5, rating: 5.0 },
];

export const INITIAL_SETTINGS: BusinessSettings = {
  id: 'settings',
  businessName: 'ACME Electronics',
  ownerName: 'Kishan Khanpara',
  currencySymbol: '$',
  currencyCode: 'USD',
  language: 'en',
  theme: 'dark',
  taxRate: 8.5,
  primaryLocationId: 'loc_downtown',
  address: '742 Evergreen Terrace, Suite 100',
  phone: '+1 (555) 019-2834',
  email: 'ops@acmeelectronics.io',
  demoMode: true,
};

export const INITIAL_LOCATIONS: Location[] = [
  { id: 'loc_downtown', name: 'Downtown Flagship', code: 'DT-01', address: '120 Market St, San Francisco, CA', isMain: true },
  { id: 'loc_westside', name: 'Westside Outlet', code: 'WS-02', address: '450 Sunset Blvd, Los Angeles, CA' },
  { id: 'loc_warehouse', name: 'Central Warehouse', code: 'WH-03', address: '880 Industrial Way, Oakland, CA' },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_peripherals', name: 'Computer Peripherals', description: 'Mice, Keyboards, Audio, Accessories' },
  { id: 'cat_audio', name: 'Audio & Acoustics', description: 'Headphones, Speakers, Microphones' },
  { id: 'cat_displays', name: 'Monitors & Displays', description: '4K Monitors, Portable Screens' },
  { id: 'cat_cables', name: 'Cables & Hubs', description: 'USB-C Adapters, Docking Stations' },
  { id: 'cat_power', name: 'Power & Charging', description: 'Power Banks, GaN Chargers, MagSafe' },
  { id: 'cat_smarthome', name: 'Smart Home & IoT', description: 'Smart Plugs, IoT Hubs, Sensors' },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  { id: 'sup_logitech', name: 'Logitech Global Distribution', contactPerson: 'Sarah Jenkins', email: 'orders@logitech-dist.com', phone: '+1 800-555-0111', address: '7700 Gateway Blvd, Newark, CA', leadTimeDays: 5, rating: 4.8 },
  { id: 'sup_anker', name: 'Anker Direct Logistics', contactPerson: 'David Chen', email: 'b2b@anker.com', phone: '+1 800-555-0222', address: '123 Tech Park, San Jose, CA', leadTimeDays: 3, rating: 4.9 },
  { id: 'sup_samsung', name: 'Samsung Electronics America', contactPerson: 'Michael Vance', email: 'supply@samsung.com', phone: '+1 800-555-0333', address: '85 Challenger Rd, Ridgefield Park, NJ', leadTimeDays: 7, rating: 4.7 },
  { id: 'sup_keychron', name: 'Keychron Supply Co', contactPerson: 'Elena Rostova', email: 'wholesale@keychron.com', phone: '+1 800-555-0444', address: '200 Logistics Dr, Austin, TX', leadTimeDays: 10, rating: 4.6 },
  { id: 'sup_bose', name: 'Bose Commercial Sales', contactPerson: 'Robert Miller', email: 'b2b@bose.com', phone: '+1 800-555-0555', address: '1 Mountain Rd, Framingham, MA', leadTimeDays: 6, rating: 4.9 },
];

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Pro Wireless Precision Mouse',
    sku: 'LOG-MX3S-GRY',
    barcode: '883920194821',
    description: 'Ergonomic 8K DPI silent click wireless mouse with electromagnetic scroll.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 58.00,
    retailPrice: 99.99,
    stockQuantity: 42,
    reorderPoint: 15,
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 20, loc_westside: 12, loc_warehouse: 10 },
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_2',
    name: 'Keychron K2 Mechanical Keyboard',
    sku: 'KEY-K2-GATERON',
    barcode: '883920194822',
    description: '75% Layout Wireless Mechanical Keyboard with Gateron Brown Switches.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 62.50,
    retailPrice: 119.00,
    stockQuantity: 18,
    reorderPoint: 10,
    supplierId: 'sup_keychron',
    supplierName: 'Keychron Supply Co',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 8, loc_westside: 4, loc_warehouse: 6 },
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_3',
    name: 'Anker 737 GaN 120W Charger',
    sku: 'ANK-737-120W',
    barcode: '883920194823',
    description: '3-Port Compact Fast Charger for Laptops, Tablets and Phones.',
    categoryId: 'cat_power',
    categoryName: 'Power & Charging',
    costPrice: 42.00,
    retailPrice: 89.99,
    stockQuantity: 6,
    reorderPoint: 12,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=300&auto=format&fit=crop&q=80',
    status: 'Low Stock',
    locationQuantities: { loc_downtown: 3, loc_westside: 1, loc_warehouse: 2 },
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(80),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_4',
    name: 'Bose QuietComfort Ultra Headphones',
    sku: 'BOS-QCU-BLK',
    barcode: '883920194824',
    description: 'World-class active noise cancelling wireless headphones with Spatial Audio.',
    categoryId: 'cat_audio',
    categoryName: 'Audio & Acoustics',
    costPrice: 240.00,
    retailPrice: 429.00,
    stockQuantity: 24,
    reorderPoint: 8,
    supplierId: 'sup_bose',
    supplierName: 'Bose Commercial Sales',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 10, loc_westside: 6, loc_warehouse: 8 },
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },
  {
    id: 'prod_5',
    name: 'Anker 10-in-1 USB-C Hub',
    sku: 'ANK-HUB-10IN1',
    barcode: '883920194825',
    description: 'Dual 4K HDMI, 100W Power Delivery, SD Card Reader & Ethernet.',
    categoryId: 'cat_cables',
    categoryName: 'Cables & Hubs',
    costPrice: 29.50,
    retailPrice: 69.99,
    stockQuantity: 0,
    reorderPoint: 15,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&auto=format&fit=crop&q=80',
    status: 'Out of Stock',
    locationQuantities: { loc_downtown: 0, loc_westside: 0, loc_warehouse: 0 },
    lastSoldAt: daysAgo(2),
    createdAt: daysAgo(95),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_6',
    name: 'Samsung Odyssey G7 28" 4K Gaming Monitor',
    sku: 'SAM-G7-4K28',
    barcode: '883920194826',
    description: '144Hz 1ms IPS 4K HDR400 HDMI 2.1 gaming display.',
    categoryId: 'cat_displays',
    categoryName: 'Monitors & Displays',
    costPrice: 380.00,
    retailPrice: 649.99,
    stockQuantity: 11,
    reorderPoint: 5,
    supplierId: 'sup_samsung',
    supplierName: 'Samsung Electronics America',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 4, loc_westside: 2, loc_warehouse: 5 },
    lastSoldAt: daysAgo(3),
    createdAt: daysAgo(110),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_7',
    name: 'Logitech Brio 4K Ultra HD Webcam',
    sku: 'LOG-BRIO-4K',
    barcode: '883920194827',
    description: 'RightLight 3 HDR, dual omni-directional microphones, noise cancellation.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 95.00,
    retailPrice: 169.99,
    stockQuantity: 31,
    reorderPoint: 10,
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 14, loc_westside: 9, loc_warehouse: 8 },
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_8',
    name: 'Smart Plug Mini 4-Pack (Matter Enabled)',
    sku: 'SMT-PLG-4PK',
    barcode: '883920194828',
    description: 'Voice control, energy monitoring, scheduling with Matter support.',
    categoryId: 'cat_smarthome',
    categoryName: 'Smart Home & IoT',
    costPrice: 18.00,
    retailPrice: 39.99,
    stockQuantity: 55,
    reorderPoint: 20,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 25, loc_westside: 15, loc_warehouse: 15 },
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(140),
    updatedAt: daysAgo(3),
  },
  {
    id: 'prod_9',
    name: 'Anker 24000mAh Power Bank 140W',
    sku: 'ANK-PB-24K-140W',
    barcode: '883920194829',
    description: 'Smart Digital Display High-Capacity Power Bank for MacBook Pro.',
    categoryId: 'cat_power',
    categoryName: 'Power & Charging',
    costPrice: 70.00,
    retailPrice: 139.99,
    stockQuantity: 15,
    reorderPoint: 8,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 7, loc_westside: 3, loc_warehouse: 5 },
    lastSoldAt: daysAgo(2),
    createdAt: daysAgo(70),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_10',
    name: 'Legacy USB-A Optical Mouse v1',
    sku: 'OLD-OPT-MSE-V1',
    barcode: '883920194830',
    description: 'Discontinued legacy wired mouse model stored in warehouse.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 5.00,
    retailPrice: 14.99,
    stockQuantity: 85,
    reorderPoint: 0,
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&auto=format&fit=crop&q=80',
    status: 'Dead Stock',
    locationQuantities: { loc_downtown: 0, loc_westside: 0, loc_warehouse: 85 },
    lastSoldAt: daysAgo(180),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(100),
  },
  {
    id: 'prod_11',
    name: 'Thunderbolt 4 Pro Cable (2m)',
    sku: 'ANK-TB4-2M',
    barcode: '883920194831',
    description: '40Gbps Data Transfer, 8K Video, 100W Charging braided cable.',
    categoryId: 'cat_cables',
    categoryName: 'Cables & Hubs',
    costPrice: 22.00,
    retailPrice: 49.99,
    stockQuantity: 4,
    reorderPoint: 10,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&auto=format&fit=crop&q=80',
    status: 'Low Stock',
    locationQuantities: { loc_downtown: 2, loc_westside: 1, loc_warehouse: 1 },
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_12',
    name: 'Bose SoundLink Flex Bluetooth Speaker',
    sku: 'BOS-SLF-BLU',
    barcode: '883920194832',
    description: 'Waterproof IP67 portable outdoor speaker with PositionIQ tech.',
    categoryId: 'cat_audio',
    categoryName: 'Audio & Acoustics',
    costPrice: 85.00,
    retailPrice: 149.00,
    stockQuantity: 28,
    reorderPoint: 10,
    supplierId: 'sup_bose',
    supplierName: 'Bose Commercial Sales',
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 12, loc_westside: 8, loc_warehouse: 8 },
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(2),
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'cust_1', name: 'Apex Design Studio', email: 'billing@apexdesign.co', phone: '+1 (415) 555-0192', address: '500 Howard St, San Francisco, CA', totalOrders: 14, totalRevenue: 4820.50, outstandingBalance: 0, status: 'VIP', createdAt: daysAgo(180) },
  { id: 'cust_2', name: 'Quantum Labs Inc', email: 'accounts@quantumlabs.io', phone: '+1 (408) 555-0284', address: '3200 Innovation Way, San Jose, CA', totalOrders: 8, totalRevenue: 3150.00, outstandingBalance: 450.00, status: 'Active', createdAt: daysAgo(120) },
  { id: 'cust_3', name: 'Marcus Vance', email: 'marcus.vance@gmail.com', phone: '+1 (510) 555-0391', address: '1820 Telegraph Ave, Oakland, CA', totalOrders: 3, totalRevenue: 649.97, outstandingBalance: 0, status: 'Active', createdAt: daysAgo(60) },
  { id: 'cust_4', name: 'Horizon Cloud Media', email: 'procurement@horizoncloud.com', phone: '+1 (650) 555-0482', address: '100 University Ave, Palo Alto, CA', totalOrders: 19, totalRevenue: 12890.00, outstandingBalance: 1200.00, status: 'VIP', createdAt: daysAgo(240) },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale_1001',
    saleNumber: 'SL-2026-1001',
    customerId: 'cust_1',
    customerName: 'Apex Design Studio',
    items: [
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', unitPrice: 99.99, unitCost: 58.00, quantity: 3, total: 299.97 },
      { productId: 'prod_2', productName: 'Keychron K2 Mechanical Keyboard', sku: 'KEY-K2-GATERON', unitPrice: 119.00, unitCost: 62.50, quantity: 2, total: 238.00 },
    ],
    subtotal: 537.97,
    tax: 45.73,
    discount: 0,
    total: 583.70,
    costOfGoodsSold: 299.00,
    grossProfit: 238.97,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    createdAt: daysAgo(0),
  },
  {
    id: 'sale_1002',
    saleNumber: 'SL-2026-1002',
    customerId: 'cust_3',
    customerName: 'Marcus Vance',
    items: [
      { productId: 'prod_4', productName: 'Bose QuietComfort Ultra Headphones', sku: 'BOS-QCU-BLK', unitPrice: 429.00, unitCost: 240.00, quantity: 1, total: 429.00 },
      { productId: 'prod_3', productName: 'Anker 737 GaN 120W Charger', sku: 'ANK-737-120W', unitPrice: 89.99, unitCost: 42.00, quantity: 1, total: 89.99 },
    ],
    subtotal: 518.99,
    tax: 44.11,
    discount: 20.00,
    total: 543.10,
    costOfGoodsSold: 282.00,
    grossProfit: 216.99,
    paymentMethod: 'Cash',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    createdAt: daysAgo(1),
  },
  {
    id: 'sale_1003',
    saleNumber: 'SL-2026-1003',
    customerId: 'cust_4',
    customerName: 'Horizon Cloud Media',
    items: [
      { productId: 'prod_6', productName: 'Samsung Odyssey G7 28" 4K Gaming Monitor', sku: 'SAM-G7-4K28', unitPrice: 649.99, unitCost: 380.00, quantity: 2, total: 1299.98 },
      { productId: 'prod_7', productName: 'Logitech Brio 4K Ultra HD Webcam', sku: 'LOG-BRIO-4K', unitPrice: 169.99, unitCost: 95.00, quantity: 2, total: 339.98 },
    ],
    subtotal: 1639.96,
    tax: 139.40,
    discount: 50.00,
    total: 1729.36,
    costOfGoodsSold: 950.00,
    grossProfit: 639.96,
    paymentMethod: 'Bank Transfer',
    status: 'Completed',
    locationId: 'loc_westside',
    locationName: 'Westside Outlet',
    createdAt: daysAgo(2),
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_2001',
    poNumber: 'PO-2026-081',
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    items: [
      { productId: 'prod_3', productName: 'Anker 737 GaN 120W Charger', sku: 'ANK-737-120W', unitCost: 42.00, orderedQuantity: 25, receivedQuantity: 0, total: 1050.00 },
      { productId: 'prod_5', productName: 'Anker 10-in-1 USB-C Hub', sku: 'ANK-HUB-10IN1', unitCost: 29.50, orderedQuantity: 30, receivedQuantity: 0, total: 885.00 },
    ],
    subtotal: 1935.00,
    tax: 164.48,
    total: 2099.48,
    status: 'Sent',
    expectedDate: daysAgo(-3),
    locationId: 'loc_warehouse',
    locationName: 'Central Warehouse',
    notes: 'Urgent restocking for out of stock USB-C hubs.',
    createdAt: daysAgo(3),
  },
  {
    id: 'po_2002',
    poNumber: 'PO-2026-082',
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    items: [
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', unitCost: 58.00, orderedQuantity: 20, receivedQuantity: 20, total: 1160.00 },
    ],
    subtotal: 1160.00,
    tax: 98.60,
    total: 1258.60,
    status: 'Received',
    expectedDate: daysAgo(2),
    receivedDate: daysAgo(1),
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    createdAt: daysAgo(7),
  },
];

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'sm_1',
    productId: 'prod_1',
    productName: 'Pro Wireless Precision Mouse',
    sku: 'LOG-MX3S-GRY',
    type: 'Sale',
    quantityChange: -3,
    previousStock: 45,
    newStock: 42,
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    referenceId: 'SL-2026-1001',
    createdAt: daysAgo(0),
  },
  {
    id: 'sm_2',
    productId: 'prod_3',
    productName: 'Anker 737 GaN 120W Charger',
    sku: 'ANK-737-120W',
    type: 'Sale',
    quantityChange: -1,
    previousStock: 7,
    newStock: 6,
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    referenceId: 'SL-2026-1002',
    createdAt: daysAgo(1),
  },
  {
    id: 'sm_3',
    productId: 'prod_1',
    productName: 'Pro Wireless Precision Mouse',
    sku: 'LOG-MX3S-GRY',
    type: 'Purchase',
    quantityChange: 20,
    previousStock: 25,
    newStock: 45,
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    referenceId: 'PO-2026-082',
    createdAt: daysAgo(1),
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  { id: 'exp_1', category: 'Rent & Store Utilities', amount: 3200.00, description: 'Downtown Store August Rent', date: daysAgo(5), locationId: 'loc_downtown' },
  { id: 'exp_2', category: 'Packaging & Freight', amount: 480.00, description: 'Courier & Shipping Supplies', date: daysAgo(2), locationId: 'loc_warehouse' },
  { id: 'exp_3', category: 'Software & Cloud Services', amount: 150.00, description: 'POS Terminal License', date: daysAgo(10), locationId: 'loc_downtown' },
];
