import {
  Product,
  Category,
  Supplier,
  Customer,
  Location,
  Sale,
  PurchaseOrder,
  StockMovement,
  Expense,
  BusinessSettings,
  StockTransfer,
  SalesChannel,
  FulfillmentOrder,
} from './types';

export const CLEAN_SETTINGS: BusinessSettings = {
  id: 'settings',
  businessName: 'Enterprise Store',
  ownerName: 'Store Manager',
  currencySymbol: '$',
  currencyCode: 'USD',
  language: 'en',
  theme: 'dark',
  taxRate: 8.5,
  primaryLocationId: 'loc_main',
  address: '100 Main Street, Suite 100',
  phone: '+1 (555) 010-0000',
  email: 'admin@enterprisestore.io',
  demoMode: false,
};

export const CLEAN_LOCATIONS: Location[] = [
  { id: 'loc_main', name: 'Main Store', code: 'MAIN-01', address: '100 Main Street', isMain: true },
];

export const CLEAN_CATEGORIES: Category[] = [
  { id: 'cat_gen', name: 'General Merchandise', description: 'Standard store products' },
  { id: 'cat_elec', name: 'Electronics & Tech', description: 'Electronic devices and accessories' },
  { id: 'cat_app', name: 'Apparel & Goods', description: 'Clothing, wear, and merchandise' },
];

export const CLEAN_SUPPLIERS: Supplier[] = [
  { id: 'sup_primary', name: 'Primary Wholesale Supplier', contactPerson: 'Account Representative', email: 'orders@wholesalesupplier.com', phone: '+1 800-555-0100', address: '500 Logistics Way', leadTimeDays: 5, rating: 5.0 },
];

export const INITIAL_SETTINGS: BusinessSettings = {
  id: 'settings',
  businessName: 'ACME Retail & Tech',
  ownerName: 'Kishan Khanpara',
  currencySymbol: '$',
  currencyCode: 'USD',
  language: 'en',
  theme: 'dark',
  taxRate: 8.5,
  primaryLocationId: 'loc_downtown',
  address: '742 Evergreen Terrace, Suite 100',
  phone: '+1 (555) 019-2834',
  email: 'ops@acmeelectronics.io',
  demoMode: true,
};

export const INITIAL_LOCATIONS: Location[] = [
  { id: 'loc_downtown', name: 'Downtown Flagship', code: 'DT-01', address: '120 Market St, San Francisco, CA', isMain: true },
  { id: 'loc_westside', name: 'Westside Outlet', code: 'WS-02', address: '450 Sunset Blvd, Los Angeles, CA' },
  { id: 'loc_warehouse', name: 'Central Warehouse', code: 'WH-03', address: '880 Industrial Way, Oakland, CA' },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_peripherals', name: 'Computer Peripherals', description: 'Mice, Keyboards, Audio, Accessories' },
  { id: 'cat_audio', name: 'Audio & Acoustics', description: 'Headphones, Speakers, Microphones' },
  { id: 'cat_displays', name: 'Monitors & Displays', description: '4K Monitors, Portable Screens' },
  { id: 'cat_cables', name: 'Cables & Hubs', description: 'USB-C Adapters, Docking Stations' },
  { id: 'cat_power', name: 'Power & Charging', description: 'Power Banks, GaN Chargers, MagSafe' },
  { id: 'cat_smarthome', name: 'Smart Home & IoT', description: 'Smart Plugs, IoT Hubs, Sensors' },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  { id: 'sup_logitech', name: 'Logitech Global Distribution', contactPerson: 'Sarah Jenkins', email: 'orders@logitech-dist.com', phone: '+1 800-555-0111', address: '7700 Gateway Blvd, Newark, CA', leadTimeDays: 5, rating: 4.8 },
  { id: 'sup_anker', name: 'Anker Direct Logistics', contactPerson: 'David Chen', email: 'b2b@anker.com', phone: '+1 800-555-0222', address: '123 Tech Park, San Jose, CA', leadTimeDays: 3, rating: 4.9 },
  { id: 'sup_samsung', name: 'Samsung Electronics America', contactPerson: 'Michael Vance', email: 'supply@samsung.com', phone: '+1 800-555-0333', address: '85 Challenger Rd, Ridgefield Park, NJ', leadTimeDays: 7, rating: 4.7 },
  { id: 'sup_keychron', name: 'Keychron Supply Co', contactPerson: 'Elena Rostova', email: 'wholesale@keychron.com', phone: '+1 800-555-0444', address: '200 Logistics Dr, Austin, TX', leadTimeDays: 10, rating: 4.6 },
  { id: 'sup_bose', name: 'Bose Commercial Sales', contactPerson: 'Robert Miller', email: 'b2b@bose.com', phone: '+1 800-555-0555', address: '1 Mountain Rd, Framingham, MA', leadTimeDays: 6, rating: 4.9 },
];

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAhead = (d: number) => new Date(now.getTime() + d * 86400000).toISOString();

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Pro Wireless Precision Mouse',
    sku: 'LOG-MX3S-GRY',
    barcode: '883920194821',
    description: 'Ergonomic 8K DPI silent click wireless mouse with electromagnetic scroll.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 58.00,
    retailPrice: 99.99,
    stockQuantity: 42,
    reorderPoint: 15,
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 20, loc_westside: 12, loc_warehouse: 10 },
    locationReorderPoints: { loc_downtown: 10, loc_westside: 6, loc_warehouse: 8 },
    variants: [
      { id: 'var_1a', name: 'Space Gray / Standard', sku: 'LOG-MX3S-GRY', barcode: '883920194821', costPrice: 58.00, retailPrice: 99.99, stockQuantity: 28, attributes: { Color: 'Space Gray', Edition: 'Standard' } },
      { id: 'var_1b', name: 'Pale Gray / Mac Edition', sku: 'LOG-MX3S-MAC', barcode: '883920194899', costPrice: 62.00, retailPrice: 109.99, stockQuantity: 14, attributes: { Color: 'Pale Gray', Edition: 'Mac Edition' } },
    ],
    customFields: {
      Sensor: 'Darkfield 8000 DPI',
      Connectivity: 'Bluetooth & Logi Bolt',
      BatteryLife: '70 Days USB-C Fast Charge',
      Warranty: '2 Years Manufacturer',
    },
    lotNumber: 'LOT-2026-MX3',
    batchNumber: 'BATCH-88A',
    expirationDate: daysAhead(720),
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_2',
    name: 'Keychron K2 Mechanical Keyboard',
    sku: 'KEY-K2-GATERON',
    barcode: '883920194822',
    description: '75% Layout Wireless Mechanical Keyboard with Gateron Brown Switches.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 62.50,
    retailPrice: 119.00,
    stockQuantity: 18,
    reorderPoint: 10,
    supplierId: 'sup_keychron',
    supplierName: 'Keychron Supply Co',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 8, loc_westside: 4, loc_warehouse: 6 },
    locationReorderPoints: { loc_downtown: 5, loc_westside: 3, loc_warehouse: 4 },
    variants: [
      { id: 'var_2a', name: 'Gateron Brown (Tactile)', sku: 'KEY-K2-BRN', barcode: '883920194822', costPrice: 62.50, retailPrice: 119.00, stockQuantity: 10, attributes: { Switch: 'Brown Tactile', Backlight: 'RGB' } },
      { id: 'var_2b', name: 'Gateron Red (Linear)', sku: 'KEY-K2-RED', barcode: '883920194898', costPrice: 62.50, retailPrice: 119.00, stockQuantity: 8, attributes: { Switch: 'Red Linear', Backlight: 'White LED' } },
    ],
    customFields: {
      Layout: '75% Compact',
      Keycaps: 'Double-Shot PBT',
      HotSwappable: 'Yes (5-pin)',
    },
    lotNumber: 'LOT-2026-KEY2',
    batchNumber: 'BATCH-04',
    expirationDate: daysAhead(1000),
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_3',
    name: 'Anker 737 GaN 120W Charger',
    sku: 'ANK-737-120W',
    barcode: '883920194823',
    description: '3-Port Compact Fast Charger for Laptops, Tablets and Phones.',
    categoryId: 'cat_power',
    categoryName: 'Power & Charging',
    costPrice: 42.00,
    retailPrice: 89.99,
    stockQuantity: 6,
    reorderPoint: 12,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=300&auto=format&fit=crop&q=80',
    status: 'Low Stock',
    locationQuantities: { loc_downtown: 3, loc_westside: 1, loc_warehouse: 2 },
    locationReorderPoints: { loc_downtown: 6, loc_westside: 3, loc_warehouse: 5 },
    customFields: {
      PowerOutput: '120W Max GaNPrime',
      Ports: '2x USB-C, 1x USB-A',
      SafetyTech: 'ActiveShield 2.0 Temperature Monitor',
    },
    lotNumber: 'LOT-ANK-120W',
    batchNumber: 'B-772',
    expirationDate: daysAhead(600),
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(80),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_4',
    name: 'Bose QuietComfort Ultra Headphones',
    sku: 'BOS-QCU-BLK',
    barcode: '883920194824',
    description: 'World-class active noise cancelling wireless headphones with Spatial Audio.',
    categoryId: 'cat_audio',
    categoryName: 'Audio & Acoustics',
    costPrice: 240.00,
    retailPrice: 429.00,
    stockQuantity: 24,
    reorderPoint: 8,
    supplierId: 'sup_bose',
    supplierName: 'Bose Commercial Sales',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 10, loc_westside: 6, loc_warehouse: 8 },
    locationReorderPoints: { loc_downtown: 4, loc_westside: 2, loc_warehouse: 3 },
    variants: [
      { id: 'var_4a', name: 'Black Velvet', sku: 'BOS-QCU-BLK', barcode: '883920194824', costPrice: 240.00, retailPrice: 429.00, stockQuantity: 16, attributes: { Color: 'Black' } },
      { id: 'var_4b', name: 'White Smoke', sku: 'BOS-QCU-WHT', barcode: '883920194897', costPrice: 240.00, retailPrice: 429.00, stockQuantity: 8, attributes: { Color: 'White Smoke' } },
    ],
    customFields: {
      NoiseCancelling: 'CustomTune Audio Calibration',
      SpatialAudio: 'Immersive Mode Enabled',
      Battery: '24 Hours Playtime',
    },
    lotNumber: 'LOT-BOSE-QC',
    batchNumber: 'BATCH-QC01',
    expirationDate: daysAhead(900),
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
  },
  {
    id: 'prod_5',
    name: 'Anker 10-in-1 USB-C Hub',
    sku: 'ANK-HUB-10IN1',
    barcode: '883920194825',
    description: 'Dual 4K HDMI, 100W Power Delivery, SD Card Reader & Ethernet.',
    categoryId: 'cat_cables',
    categoryName: 'Cables & Hubs',
    costPrice: 29.50,
    retailPrice: 69.99,
    stockQuantity: 0,
    reorderPoint: 15,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&auto=format&fit=crop&q=80',
    status: 'Out of Stock',
    locationQuantities: { loc_downtown: 0, loc_westside: 0, loc_warehouse: 0 },
    locationReorderPoints: { loc_downtown: 8, loc_westside: 4, loc_warehouse: 6 },
    customFields: {
      HDMI: 'Dual 4K @ 60Hz',
      Ethernet: 'Gigabit 1000Mbps',
      PD: '100W Pass-Through',
    },
    lotNumber: 'LOT-HUB-10',
    batchNumber: 'BATCH-2025',
    expirationDate: daysAhead(400),
    lastSoldAt: daysAgo(2),
    createdAt: daysAgo(95),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_6',
    name: 'Samsung Odyssey G7 28" 4K Gaming Monitor',
    sku: 'SAM-G7-4K28',
    barcode: '883920194826',
    description: '144Hz 1ms IPS 4K HDR400 HDMI 2.1 gaming display.',
    categoryId: 'cat_displays',
    categoryName: 'Monitors & Displays',
    costPrice: 380.00,
    retailPrice: 649.99,
    stockQuantity: 11,
    reorderPoint: 5,
    supplierId: 'sup_samsung',
    supplierName: 'Samsung Electronics America',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 4, loc_westside: 2, loc_warehouse: 5 },
    locationReorderPoints: { loc_downtown: 2, loc_westside: 1, loc_warehouse: 2 },
    customFields: {
      Resolution: '3840 x 2160 (4K UHD)',
      RefreshRate: '144Hz',
      ResponseTime: '1ms GtG',
      SyncTech: 'NVIDIA G-Sync & FreeSync Premium Pro',
    },
    lotNumber: 'LOT-SAM-G7',
    batchNumber: 'B-G744',
    expirationDate: daysAhead(1200),
    lastSoldAt: daysAgo(3),
    createdAt: daysAgo(110),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_7',
    name: 'Logitech Brio 4K Ultra HD Webcam',
    sku: 'LOG-BRIO-4K',
    barcode: '883920194827',
    description: 'RightLight 3 HDR, dual omni-directional microphones, noise cancellation.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 95.00,
    retailPrice: 169.99,
    stockQuantity: 31,
    reorderPoint: 10,
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 14, loc_westside: 9, loc_warehouse: 8 },
    locationReorderPoints: { loc_downtown: 6, loc_westside: 3, loc_warehouse: 4 },
    customFields: {
      Resolution: '4K Ultra HD @ 30fps / 1080p @ 60fps',
      FieldOfView: 'Adjustable 65°, 78°, 90°',
      WindowsHello: 'Infrared Facial Recognition Support',
    },
    lotNumber: 'LOT-BRIO-4K',
    batchNumber: 'B-098',
    expirationDate: daysAhead(800),
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_8',
    name: 'Smart Plug Mini 4-Pack (Matter Enabled)',
    sku: 'SMT-PLG-4PK',
    barcode: '883920194828',
    description: 'Voice control, energy monitoring, scheduling with Matter support.',
    categoryId: 'cat_smarthome',
    categoryName: 'Smart Home & IoT',
    costPrice: 18.00,
    retailPrice: 39.99,
    stockQuantity: 55,
    reorderPoint: 20,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 25, loc_westside: 15, loc_warehouse: 15 },
    locationReorderPoints: { loc_downtown: 10, loc_westside: 6, loc_warehouse: 8 },
    customFields: {
      Protocol: 'Matter over Wi-Fi (2.4GHz)',
      EnergyMonitoring: 'Real-Time Wattage Tracker in App',
      MaxLoad: '15A / 1800W',
    },
    lotNumber: 'LOT-PLUG-MTR',
    batchNumber: 'BATCH-882',
    expirationDate: daysAhead(1100),
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(140),
    updatedAt: daysAgo(3),
  },
  {
    id: 'prod_9',
    name: 'Anker 24000mAh Power Bank 140W',
    sku: 'ANK-PB-24K-140W',
    barcode: '883920194829',
    description: 'Smart Digital Display High-Capacity Power Bank for MacBook Pro.',
    categoryId: 'cat_power',
    categoryName: 'Power & Charging',
    costPrice: 70.00,
    retailPrice: 139.99,
    stockQuantity: 15,
    reorderPoint: 8,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 7, loc_westside: 3, loc_warehouse: 5 },
    locationReorderPoints: { loc_downtown: 4, loc_westside: 2, loc_warehouse: 3 },
    customFields: {
      Capacity: '24,000mAh / 86.4Wh (Airline Safe)',
      Display: 'Smart Digital Display with input/output watts',
    },
    lotNumber: 'LOT-PB-24K',
    batchNumber: 'B-991',
    expirationDate: daysAhead(450),
    lastSoldAt: daysAgo(2),
    createdAt: daysAgo(70),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_10',
    name: 'Legacy USB-A Optical Mouse v1',
    sku: 'OLD-OPT-MSE-V1',
    barcode: '883920194830',
    description: 'Discontinued legacy wired mouse model stored in warehouse.',
    categoryId: 'cat_peripherals',
    categoryName: 'Computer Peripherals',
    costPrice: 5.00,
    retailPrice: 14.99,
    stockQuantity: 85,
    reorderPoint: 0,
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&auto=format&fit=crop&q=80',
    status: 'Dead Stock',
    locationQuantities: { loc_downtown: 0, loc_westside: 0, loc_warehouse: 85 },
    locationReorderPoints: { loc_downtown: 0, loc_westside: 0, loc_warehouse: 0 },
    customFields: {
      Condition: 'Surplus Warehouse Clearance',
      Connectivity: 'USB-A 2.0 Wired',
    },
    lotNumber: 'LOT-OLD-2023',
    batchNumber: 'BATCH-SURPLUS',
    expirationDate: daysAgo(30), // Expired lot for testing recall & expiry filters
    lastSoldAt: daysAgo(180),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(100),
  },
  {
    id: 'prod_11',
    name: 'Thunderbolt 4 Pro Cable (2m)',
    sku: 'ANK-TB4-2M',
    barcode: '883920194831',
    description: '40Gbps Data Transfer, 8K Video, 100W Charging braided cable.',
    categoryId: 'cat_cables',
    categoryName: 'Cables & Hubs',
    costPrice: 22.00,
    retailPrice: 49.99,
    stockQuantity: 4,
    reorderPoint: 10,
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&auto=format&fit=crop&q=80',
    status: 'Low Stock',
    locationQuantities: { loc_downtown: 2, loc_westside: 1, loc_warehouse: 1 },
    locationReorderPoints: { loc_downtown: 5, loc_westside: 3, loc_warehouse: 4 },
    customFields: {
      Length: '2.0 Meters (6.6 ft)',
      Bandwidth: '40 Gbps PCIe',
      Power: '100W Power Delivery 3.0',
    },
    lotNumber: 'LOT-TB4-2M',
    batchNumber: 'BATCH-002',
    expirationDate: daysAhead(950),
    lastSoldAt: daysAgo(0),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_12',
    name: 'Bose SoundLink Flex Bluetooth Speaker',
    sku: 'BOS-SLF-BLU',
    barcode: '883920194832',
    description: 'Waterproof IP67 portable outdoor speaker with PositionIQ tech.',
    categoryId: 'cat_audio',
    categoryName: 'Audio & Acoustics',
    costPrice: 85.00,
    retailPrice: 149.00,
    stockQuantity: 28,
    reorderPoint: 10,
    supplierId: 'sup_bose',
    supplierName: 'Bose Commercial Sales',
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=300&auto=format&fit=crop&q=80',
    status: 'Healthy',
    locationQuantities: { loc_downtown: 12, loc_westside: 8, loc_warehouse: 8 },
    locationReorderPoints: { loc_downtown: 5, loc_westside: 3, loc_warehouse: 4 },
    variants: [
      { id: 'var_12a', name: 'Stone Blue', sku: 'BOS-SLF-BLU', barcode: '883920194832', costPrice: 85.00, retailPrice: 149.00, stockQuantity: 18, attributes: { Color: 'Stone Blue' } },
      { id: 'var_12b', name: 'Black Carmine', sku: 'BOS-SLF-BLK', barcode: '883920194896', costPrice: 85.00, retailPrice: 149.00, stockQuantity: 10, attributes: { Color: 'Black Carmine' } },
    ],
    customFields: {
      WaterproofRating: 'IP67 Dust & Waterproof (Floats)',
      Battery: '12 Hours Lithium-Ion',
    },
    lotNumber: 'LOT-BOSE-SL',
    batchNumber: 'B-SL88',
    expirationDate: daysAhead(700),
    lastSoldAt: daysAgo(1),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(2),
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'cust_1', name: 'Apex Design Studio', email: 'billing@apexdesign.co', phone: '+1 (415) 555-0192', address: '500 Howard St, San Francisco, CA', totalOrders: 14, totalRevenue: 4820.50, outstandingBalance: 0, status: 'VIP', createdAt: daysAgo(180) },
  { id: 'cust_2', name: 'Quantum Labs Inc', email: 'accounts@quantumlabs.io', phone: '+1 (408) 555-0284', address: '3200 Innovation Way, San Jose, CA', totalOrders: 8, totalRevenue: 3150.00, outstandingBalance: 450.00, status: 'Active', createdAt: daysAgo(120) },
  { id: 'cust_3', name: 'Marcus Vance', email: 'marcus.vance@gmail.com', phone: '+1 (510) 555-0391', address: '1820 Telegraph Ave, Oakland, CA', totalOrders: 3, totalRevenue: 649.97, outstandingBalance: 0, status: 'Active', createdAt: daysAgo(60) },
  { id: 'cust_4', name: 'Horizon Cloud Media', email: 'procurement@horizoncloud.com', phone: '+1 (650) 555-0482', address: '100 University Ave, Palo Alto, CA', totalOrders: 19, totalRevenue: 12890.00, outstandingBalance: 1200.00, status: 'VIP', createdAt: daysAgo(240) },
];

export const INITIAL_SALES_CHANNELS: SalesChannel[] = [
  { id: 'chan_pos', name: 'In-Store POS', icon: 'Store', status: 'Connected', lastSyncedAt: daysAgo(0), activeListingsCount: 12, pendingOrdersCount: 0, autoSyncInventory: true },
  { id: 'chan_shopify', name: 'Shopify', icon: 'ShoppingBag', status: 'Connected', lastSyncedAt: daysAgo(0), activeListingsCount: 12, pendingOrdersCount: 3, autoSyncInventory: true },
  { id: 'chan_amazon', name: 'Amazon', icon: 'Globe', status: 'Connected', lastSyncedAt: daysAgo(0), activeListingsCount: 10, pendingOrdersCount: 2, autoSyncInventory: true },
  { id: 'chan_ebay', name: 'eBay', icon: 'Tag', status: 'Connected', lastSyncedAt: daysAgo(1), activeListingsCount: 8, pendingOrdersCount: 1, autoSyncInventory: true },
  { id: 'chan_woo', name: 'WooCommerce', icon: 'ShoppingCart', status: 'Connected', lastSyncedAt: daysAgo(1), activeListingsCount: 12, pendingOrdersCount: 1, autoSyncInventory: false },
];

export const INITIAL_FULFILLMENT_ORDERS: FulfillmentOrder[] = [
  {
    id: 'ful_101',
    orderNumber: 'SH-89421',
    channel: 'Shopify',
    customerName: 'Claire Redfield',
    customerEmail: 'claire.r@terrasave.org',
    shippingAddress: '740 Raccoon Street, Boston, MA 02108',
    items: [
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', quantity: 2, unitPrice: 99.99 },
      { productId: 'prod_3', productName: 'Anker 737 GaN 120W Charger', sku: 'ANK-737-120W', quantity: 1, unitPrice: 89.99 },
    ],
    totalAmount: 289.97,
    status: 'Pending',
    assignedLocationId: 'loc_warehouse',
    assignedLocationName: 'Central Warehouse',
    createdAt: daysAgo(0),
  },
  {
    id: 'ful_102',
    orderNumber: 'AMZ-55102',
    channel: 'Amazon',
    customerName: 'Leon S. Kennedy',
    customerEmail: 'lsk@dsogov.us',
    shippingAddress: '1600 Pennsylvania Ave, Washington, DC 20500',
    items: [
      { productId: 'prod_4', productName: 'Bose QuietComfort Ultra Headphones', sku: 'BOS-QCU-BLK', quantity: 1, unitPrice: 429.00 },
    ],
    totalAmount: 429.00,
    status: 'Picking',
    carrier: 'UPS',
    trackingNumber: '1Z9999999999999999',
    assignedLocationId: 'loc_downtown',
    assignedLocationName: 'Downtown Flagship',
    createdAt: daysAgo(0),
  },
  {
    id: 'ful_103',
    orderNumber: 'EB-33921',
    channel: 'eBay',
    customerName: 'Jill Valentine',
    customerEmail: 'jill.v@bsaa-ops.org',
    shippingAddress: '42 Perimeter Way, Atlanta, GA 30339',
    items: [
      { productId: 'prod_2', productName: 'Keychron K2 Mechanical Keyboard', sku: 'KEY-K2-GATERON', quantity: 1, unitPrice: 119.00 },
      { productId: 'prod_7', productName: 'Logitech Brio 4K Ultra HD Webcam', sku: 'LOG-BRIO-4K', quantity: 1, unitPrice: 169.99 },
    ],
    totalAmount: 288.99,
    status: 'Packed',
    carrier: 'FedEx',
    trackingNumber: '772910482910',
    assignedLocationId: 'loc_warehouse',
    assignedLocationName: 'Central Warehouse',
    createdAt: daysAgo(1),
  },
  {
    id: 'ful_104',
    orderNumber: 'SH-89410',
    channel: 'Shopify',
    customerName: 'Chris Redfield',
    customerEmail: 'chris.r@bsaa-intl.org',
    shippingAddress: '900 North Lake Shore Dr, Chicago, IL 60611',
    items: [
      { productId: 'prod_6', productName: 'Samsung Odyssey G7 28" 4K Gaming Monitor', sku: 'SAM-G7-4K28', quantity: 1, unitPrice: 649.99 },
    ],
    totalAmount: 649.99,
    status: 'Shipped',
    carrier: 'DHL',
    trackingNumber: 'DHL-US-9920194',
    assignedLocationId: 'loc_warehouse',
    assignedLocationName: 'Central Warehouse',
    createdAt: daysAgo(2),
    shippedAt: daysAgo(1),
  },
];

export const INITIAL_SALES: Sale[] = [
  // Today's Sales
  {
    id: 'sale_1001',
    saleNumber: 'SL-2026-1001',
    customerId: 'cust_1',
    customerName: 'Apex Design Studio',
    items: [
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', unitPrice: 99.99, unitCost: 58.00, quantity: 2, total: 199.98 },
      { productId: 'prod_2', productName: 'Keychron K2 Mechanical Keyboard', sku: 'KEY-K2-GATERON', unitPrice: 119.00, unitCost: 62.50, quantity: 1, total: 119.00 },
    ],
    subtotal: 318.98,
    tax: 27.11,
    discount: 0,
    total: 346.09,
    costOfGoodsSold: 178.50,
    grossProfit: 140.48,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    channel: 'In-Store POS',
    createdAt: hoursAgo(1),
  },
  {
    id: 'sale_1002',
    saleNumber: 'SL-2026-1002',
    customerId: 'cust_3',
    customerName: 'Marcus Vance',
    items: [
      { productId: 'prod_3', productName: 'Anker 737 GaN 120W Charger', sku: 'ANK-737-120W', unitPrice: 89.99, unitCost: 42.00, quantity: 2, total: 179.98 },
    ],
    subtotal: 179.98,
    tax: 15.30,
    discount: 10.00,
    total: 185.28,
    costOfGoodsSold: 84.00,
    grossProfit: 95.98,
    paymentMethod: 'Cash',
    status: 'Completed',
    locationId: 'loc_westside',
    locationName: 'Westside Outlet',
    channel: 'In-Store POS',
    createdAt: hoursAgo(3),
  },
  {
    id: 'sale_1003',
    saleNumber: 'SL-2026-1003',
    customerId: 'cust_2',
    customerName: 'Quantum Labs Inc',
    items: [
      { productId: 'prod_4', productName: 'Bose QuietComfort Ultra Headphones', sku: 'BOS-QCU-BLK', unitPrice: 429.00, unitCost: 240.00, quantity: 1, total: 429.00 },
    ],
    subtotal: 429.00,
    tax: 36.47,
    discount: 0,
    total: 465.47,
    costOfGoodsSold: 240.00,
    grossProfit: 189.00,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    channel: 'In-Store POS',
    createdAt: hoursAgo(5),
  },
  {
    id: 'sale_1004',
    saleNumber: 'SL-2026-1004',
    customerId: 'cust_4',
    customerName: 'Horizon Cloud Media',
    items: [
      { productId: 'prod_7', productName: 'Logitech Brio 4K Ultra HD Webcam', sku: 'LOG-BRIO-4K', unitPrice: 169.99, unitCost: 95.00, quantity: 2, total: 339.98 },
      { productId: 'prod_8', productName: 'Smart Plug Mini 4-Pack (Matter Enabled)', sku: 'SMT-PLG-4PK', unitPrice: 39.99, unitCost: 18.00, quantity: 3, total: 119.97 },
    ],
    subtotal: 459.95,
    tax: 39.10,
    discount: 20.00,
    total: 479.05,
    costOfGoodsSold: 244.00,
    grossProfit: 215.95,
    paymentMethod: 'Bank Transfer',
    status: 'Completed',
    locationId: 'loc_warehouse',
    locationName: 'Central Warehouse',
    channel: 'Shopify',
    createdAt: hoursAgo(7),
  },

  // Past Week Sales
  {
    id: 'sale_1005',
    saleNumber: 'SL-2026-1005',
    customerId: 'cust_1',
    customerName: 'Apex Design Studio',
    items: [
      { productId: 'prod_6', productName: 'Samsung Odyssey G7 28" 4K Gaming Monitor', sku: 'SAM-G7-4K28', unitPrice: 649.99, unitCost: 380.00, quantity: 1, total: 649.99 },
    ],
    subtotal: 649.99,
    tax: 55.25,
    discount: 0,
    total: 705.24,
    costOfGoodsSold: 380.00,
    grossProfit: 269.99,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    channel: 'In-Store POS',
    createdAt: daysAgo(1),
  },
  {
    id: 'sale_1006',
    saleNumber: 'SL-2026-1006',
    customerId: 'cust_3',
    customerName: 'Marcus Vance',
    items: [
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', unitPrice: 99.99, unitCost: 58.00, quantity: 1, total: 99.99 },
      { productId: 'prod_9', productName: 'Anker 24000mAh Power Bank 140W', sku: 'ANK-PB-24K-140W', unitPrice: 139.99, unitCost: 70.00, quantity: 1, total: 139.99 },
    ],
    subtotal: 239.98,
    tax: 20.40,
    discount: 0,
    total: 260.38,
    costOfGoodsSold: 128.00,
    grossProfit: 111.98,
    paymentMethod: 'Cash',
    status: 'Completed',
    locationId: 'loc_westside',
    locationName: 'Westside Outlet',
    channel: 'In-Store POS',
    createdAt: daysAgo(2),
  },
  {
    id: 'sale_1007',
    saleNumber: 'SL-2026-1007',
    customerId: 'cust_2',
    customerName: 'Quantum Labs Inc',
    items: [
      { productId: 'prod_2', productName: 'Keychron K2 Mechanical Keyboard', sku: 'KEY-K2-GATERON', unitPrice: 119.00, unitCost: 62.50, quantity: 4, total: 476.00 },
      { productId: 'prod_12', productName: 'Bose SoundLink Flex Bluetooth Speaker', sku: 'BOS-SLF-BLU', unitPrice: 149.00, unitCost: 85.00, quantity: 2, total: 298.00 },
    ],
    subtotal: 774.00,
    tax: 65.79,
    discount: 30.00,
    total: 809.79,
    costOfGoodsSold: 420.00,
    grossProfit: 354.00,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    channel: 'In-Store POS',
    createdAt: daysAgo(3),
  },
  {
    id: 'sale_1008',
    saleNumber: 'SL-2026-1008',
    customerId: 'cust_4',
    customerName: 'Horizon Cloud Media',
    items: [
      { productId: 'prod_6', productName: 'Samsung Odyssey G7 28" 4K Gaming Monitor', sku: 'SAM-G7-4K28', unitPrice: 649.99, unitCost: 380.00, quantity: 2, total: 1299.98 },
    ],
    subtotal: 1299.98,
    tax: 110.50,
    discount: 50.00,
    total: 1360.48,
    costOfGoodsSold: 760.00,
    grossProfit: 539.98,
    paymentMethod: 'Bank Transfer',
    status: 'Completed',
    locationId: 'loc_warehouse',
    locationName: 'Central Warehouse',
    channel: 'Amazon',
    createdAt: daysAgo(4),
  },
  {
    id: 'sale_1009',
    saleNumber: 'SL-2026-1009',
    customerId: 'cust_1',
    customerName: 'Apex Design Studio',
    items: [
      { productId: 'prod_4', productName: 'Bose QuietComfort Ultra Headphones', sku: 'BOS-QCU-BLK', unitPrice: 429.00, unitCost: 240.00, quantity: 2, total: 858.00 },
    ],
    subtotal: 858.00,
    tax: 72.93,
    discount: 0,
    total: 930.93,
    costOfGoodsSold: 480.00,
    grossProfit: 378.00,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_westside',
    locationName: 'Westside Outlet',
    channel: 'In-Store POS',
    createdAt: daysAgo(5),
  },
  {
    id: 'sale_1010',
    saleNumber: 'SL-2026-1010',
    customerId: 'cust_3',
    customerName: 'Marcus Vance',
    items: [
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', unitPrice: 99.99, unitCost: 58.00, quantity: 2, total: 199.98 },
    ],
    subtotal: 199.98,
    tax: 17.00,
    discount: 0,
    total: 216.98,
    costOfGoodsSold: 116.00,
    grossProfit: 83.98,
    paymentMethod: 'Cash',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    channel: 'In-Store POS',
    createdAt: daysAgo(6),
  },

  // Past Month (8 - 28 Days Ago) Sales
  {
    id: 'sale_1011',
    saleNumber: 'SL-2026-1011',
    customerId: 'cust_4',
    customerName: 'Horizon Cloud Media',
    items: [
      { productId: 'prod_6', productName: 'Samsung Odyssey G7 28" 4K Gaming Monitor', sku: 'SAM-G7-4K28', unitPrice: 649.99, unitCost: 380.00, quantity: 3, total: 1949.97 },
      { productId: 'prod_7', productName: 'Logitech Brio 4K Ultra HD Webcam', sku: 'LOG-BRIO-4K', unitPrice: 169.99, unitCost: 95.00, quantity: 3, total: 509.97 },
    ],
    subtotal: 2459.94,
    tax: 209.09,
    discount: 100.00,
    total: 2569.03,
    costOfGoodsSold: 1425.00,
    grossProfit: 1034.94,
    paymentMethod: 'Bank Transfer',
    status: 'Completed',
    locationId: 'loc_warehouse',
    locationName: 'Central Warehouse',
    channel: 'Shopify',
    createdAt: daysAgo(10),
  },
  {
    id: 'sale_1012',
    saleNumber: 'SL-2026-1012',
    customerId: 'cust_2',
    customerName: 'Quantum Labs Inc',
    items: [
      { productId: 'prod_3', productName: 'Anker 737 GaN 120W Charger', sku: 'ANK-737-120W', unitPrice: 89.99, unitCost: 42.00, quantity: 5, total: 449.95 },
      { productId: 'prod_9', productName: 'Anker 24000mAh Power Bank 140W', sku: 'ANK-PB-24K-140W', unitPrice: 139.99, unitCost: 70.00, quantity: 2, total: 279.98 },
    ],
    subtotal: 729.93,
    tax: 62.04,
    discount: 25.00,
    total: 766.97,
    costOfGoodsSold: 350.00,
    grossProfit: 379.93,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    channel: 'In-Store POS',
    createdAt: daysAgo(16),
  },
  {
    id: 'sale_1013',
    saleNumber: 'SL-2026-1013',
    customerId: 'cust_1',
    customerName: 'Apex Design Studio',
    items: [
      { productId: 'prod_4', productName: 'Bose QuietComfort Ultra Headphones', sku: 'BOS-QCU-BLK', unitPrice: 429.00, unitCost: 240.00, quantity: 3, total: 1287.00 },
    ],
    subtotal: 1287.00,
    tax: 109.40,
    discount: 50.00,
    total: 1346.40,
    costOfGoodsSold: 720.00,
    grossProfit: 567.00,
    paymentMethod: 'Card',
    status: 'Completed',
    locationId: 'loc_westside',
    locationName: 'Westside Outlet',
    channel: 'In-Store POS',
    createdAt: daysAgo(22),
  },
  {
    id: 'sale_1014',
    saleNumber: 'SL-2026-1014',
    customerId: 'cust_3',
    customerName: 'Marcus Vance',
    items: [
      { productId: 'prod_2', productName: 'Keychron K2 Mechanical Keyboard', sku: 'KEY-K2-GATERON', unitPrice: 119.00, unitCost: 62.50, quantity: 1, total: 119.00 },
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', unitPrice: 99.99, unitCost: 58.00, quantity: 1, total: 99.99 },
    ],
    subtotal: 218.99,
    tax: 18.61,
    discount: 0,
    total: 237.60,
    costOfGoodsSold: 120.50,
    grossProfit: 98.49,
    paymentMethod: 'Cash',
    status: 'Completed',
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    channel: 'In-Store POS',
    createdAt: daysAgo(28),
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_2001',
    poNumber: 'PO-2026-081',
    supplierId: 'sup_anker',
    supplierName: 'Anker Direct Logistics',
    items: [
      { productId: 'prod_3', productName: 'Anker 737 GaN 120W Charger', sku: 'ANK-737-120W', unitCost: 42.00, orderedQuantity: 25, receivedQuantity: 0, total: 1050.00 },
      { productId: 'prod_5', productName: 'Anker 10-in-1 USB-C Hub', sku: 'ANK-HUB-10IN1', unitCost: 29.50, orderedQuantity: 30, receivedQuantity: 0, total: 885.00 },
    ],
    subtotal: 1935.00,
    tax: 164.48,
    total: 2099.48,
    status: 'Sent',
    expectedDate: daysAgo(-3),
    locationId: 'loc_warehouse',
    locationName: 'Central Warehouse',
    notes: 'Urgent restocking for out of stock USB-C hubs.',
    createdAt: daysAgo(3),
  },
  {
    id: 'po_2002',
    poNumber: 'PO-2026-082',
    supplierId: 'sup_logitech',
    supplierName: 'Logitech Global Distribution',
    items: [
      { productId: 'prod_1', productName: 'Pro Wireless Precision Mouse', sku: 'LOG-MX3S-GRY', unitCost: 58.00, orderedQuantity: 20, receivedQuantity: 20, total: 1160.00 },
    ],
    subtotal: 1160.00,
    tax: 98.60,
    total: 1258.60,
    status: 'Received',
    expectedDate: daysAgo(2),
    receivedDate: daysAgo(1),
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    createdAt: daysAgo(7),
  },
];

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'sm_1',
    productId: 'prod_1',
    productName: 'Pro Wireless Precision Mouse',
    sku: 'LOG-MX3S-GRY',
    type: 'Sale',
    quantityChange: -3,
    previousStock: 45,
    newStock: 42,
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    referenceId: 'SL-2026-1001',
    createdAt: daysAgo(0),
  },
  {
    id: 'sm_2',
    productId: 'prod_3',
    productName: 'Anker 737 GaN 120W Charger',
    sku: 'ANK-737-120W',
    type: 'Sale',
    quantityChange: -1,
    previousStock: 7,
    newStock: 6,
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    referenceId: 'SL-2026-1002',
    createdAt: daysAgo(1),
  },
  {
    id: 'sm_3',
    productId: 'prod_1',
    productName: 'Pro Wireless Precision Mouse',
    sku: 'LOG-MX3S-GRY',
    type: 'Purchase',
    quantityChange: 20,
    previousStock: 25,
    newStock: 45,
    locationId: 'loc_downtown',
    locationName: 'Downtown Flagship',
    referenceId: 'PO-2026-082',
    createdAt: daysAgo(1),
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  { id: 'exp_1', category: 'Rent & Store Utilities', amount: 3200.00, description: 'Downtown Store August Rent', date: daysAgo(5), locationId: 'loc_downtown' },
  { id: 'exp_2', category: 'Packaging & Freight', amount: 480.00, description: 'Courier & Shipping Supplies', date: daysAgo(2), locationId: 'loc_warehouse' },
  { id: 'exp_3', category: 'Software & Cloud Services', amount: 150.00, description: 'POS Terminal License', date: daysAgo(10), locationId: 'loc_downtown' },
];
